
    CONSTRAINT FK_Player_LIB FOREIGN KEY (Team, UID) REFERENCES Players(Team, UID),






/*
ALTER TABLE C
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE CB
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE DB
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE DE
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE DL
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE DT
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE FB
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE G
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE LB
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE LS
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE OL
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE OT
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE P
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE PK
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE QB
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE RB
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE S
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE TE
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE WR
   ADD FOREIGN KEY (No) REFERENCES Players (No);
   ADD FOREIGN KEY (Name) REFERENCES Players (Name);
   ADD FOREIGN KEY (Pos) REFERENCES Players (Pos);
   ADD FOREIGN KEY (Ht) REFERENCES Players (Ht);
   ADD FOREIGN KEY (Wt) REFERENCES Players (Wt);
   ADD FOREIGN KEY (Class) REFERENCES Players (Class);
   ADD FOREIGN KEY (Hometown) REFERENCES Players (Hometown);
   ADD FOREIGN KEY (State) REFERENCES Players (State);
   ADD FOREIGN KEY (Team) REFERENCES Players (Team);

ALTER TABLE uva
	ADD CONSTRAINT CK_minPlayer
	CHECK (COUNT(Name) >= 11)

ALTER TABLE vt
	ADD CONSTRAINT CK_minPlayer
	CHECK (COUNT(Name) >= 11)

ALTER TABLE lib
	ADD CONSTRAINT CK_minPlayer
	CHECK (COUNT(Name) >= 11)

ALTER TABLE nor
	ADD CONSTRAINT CK_minPlayer
	CHECK (COUNT(Name) >= 11)

*/