CREATE TABLE lib (
    `No` INT,
    `Name` VARCHAR(21) CHARACTER SET utf8,
    `Pos` VARCHAR(2) CHARACTER SET utf8,
    `Ht` VARCHAR(4) CHARACTER SET utf8,
    `Wt` INT,
    `Class` VARCHAR(2) CHARACTER SET utf8,
    `Hometown` VARCHAR(18) CHARACTER SET utf8,
    `State` VARCHAR(2) CHARACTER SET utf8
);
INSERT INTO lib VALUES (1,'DeCarlo Hamiltona','DT','6-3',335,'FR','Plantation','FL');
INSERT INTO lib VALUES (1,'Zac Parkera','WR','5-9',185,'SR','Reston','VA');
INSERT INTO lib VALUES (2,'Jeremy Petersa','CB','5-10',190,'SO','Green Cove Springs','FL');
INSERT INTO lib VALUES (3,'Rion Davisa','S','6-0',190,'FR','Hopkins','SC');
INSERT INTO lib VALUES (3,'Stephon Mashaa','QB','6-1',205,'JR','Marietta','GA');
INSERT INTO lib VALUES (4,'Jaylyn McKinneya','LB','6-0',225,'FR','Lake Wales','FL');
INSERT INTO lib VALUES (5,'Lucas Ironsa','LB','6-0',215,'SO','Fort Lauderdale','FL');
INSERT INTO lib VALUES (6,'Tyrin Hollowaya','CB','6-0',195,'JR','Humble','TX');
INSERT INTO lib VALUES (7,'Ceneca Espinoza Jr.a','S','6-1',200,'FR','Arlington','VA');
INSERT INTO lib VALUES (7,'Damian Kinga','WR','5-11',175,'SO','--','--');
INSERT INTO lib VALUES (8,'Jimmy Faulksa','CB','6-1',175,'FR','--','--');
INSERT INTO lib VALUES (8,'Dante Shellsa','WR','6-1',180,'SR','Camden','DE');
INSERT INTO lib VALUES (9,'Nick Newmana','LB','6-4',215,'SR','Gainesville','VA');
INSERT INTO lib VALUES (10,'Alex Proberta','PK','5-9',170,'FR','Andover','MN');
INSERT INTO lib VALUES (11,'Antonio Gandy-Goldena','WR','6-4',200,'FR','Dallas','GA');
INSERT INTO lib VALUES (11,'Cole Gibsona','PK','6-1',235,'FR','Chesapeake','VA');
INSERT INTO lib VALUES (11,'Lionell McConnella','WR','5-10',180,'FR','Allen','TX');
INSERT INTO lib VALUES (12,'Stephen Calverta','QB','6-2',180,'FR','Plantation','FL');
INSERT INTO lib VALUES (12,'Brandon Tillmona','S','6-1',210,'FR','Lexington','SC');
INSERT INTO lib VALUES (13,'Korell Evansa','LB','6-1',215,'FR','Hallandale','FL');
INSERT INTO lib VALUES (13,'Rudiger Yearicka','QB','6-3',195,'FR','Matthews','NC');
INSERT INTO lib VALUES (14,'Cam Jacksona','CB','6-1',205,'SO','Houston','TX');
INSERT INTO lib VALUES (15,'T.J. Tillerya','CB','5-10',195,'SO','Charlottesville','VA');
INSERT INTO lib VALUES (16,'Spencer Jonesa','QB','6-3',185,'FR','Nashville','TN');
INSERT INTO lib VALUES (17,'Kendall Couamina','TE','6-2',255,'JR','Miami Lakes','FL');
INSERT INTO lib VALUES (18,'Josh Newmana','WR','5-10',190,'FR','Gainesville','VA');
INSERT INTO lib VALUES (19,'Will Johnsona','TE','6-6',265,'SR','Osseo','MN');
INSERT INTO lib VALUES (20,'Solomon McGintya','S','6-2',220,'JR','Navasota','TX');
INSERT INTO lib VALUES (21,'Mitchell Lewisa','RB','6-0',220,'FR','Auburn','AL');
INSERT INTO lib VALUES (21,'Wesley Scotta','CB','5-10',175,'SR','Lorton','VA');
INSERT INTO lib VALUES (22,'Todd Macona','RB','5-10',210,'JR','--','--');
INSERT INTO lib VALUES (23,'Frankie Hicksona','RB','5-8',200,'FR','Lynchburg','VA');
INSERT INTO lib VALUES (24,'Malik Matthewsa','CB','5-11',185,'FR','Jacksonville','FL');
INSERT INTO lib VALUES (25,'Aaron Glovera','LB','5-11',210,'FR','Norfolk','VA');
INSERT INTO lib VALUES (26,'Joseph Dixona','RB','5-9',190,'SO','--','--');
INSERT INTO lib VALUES (27,'Cameron Jonesa','CB','5-11',195,'SO','New Orleans','LA');
INSERT INTO lib VALUES (28,'Corbin Jacksona','S','6-0',200,'SO','Charlotte','NC');
INSERT INTO lib VALUES (29,'David Jeremaiha','WR','0-0',0,'FR','--','--');
INSERT INTO lib VALUES (30,'Dexter Robbinsa','LB','5-11',225,'SR','Sevierville','TN');
INSERT INTO lib VALUES (31,'Elijah Bentona','S','6-1',190,'FR','Forest','VA');
INSERT INTO lib VALUES (32,'Jermaine Copelanda','CB','5-9',190,'FR','Farmville','VA');
INSERT INTO lib VALUES (33,'Didier Monciona','RB','5-8',205,'JR','MANSFIELD','CT');
INSERT INTO lib VALUES (34,'Carrington Mosleya','RB','5-11',235,'JR','Brookneal','VA');
INSERT INTO lib VALUES (35,'Trey Turnera','P','5-11',210,'JR','Rome','GA');
INSERT INTO lib VALUES (36,'Thomas Kennedya','FB','5-11',240,'JR','Roanoke','VA');
INSERT INTO lib VALUES (38,'Alpha Jalloha','S','6-1',200,'SR','New Carrollton','MD');
INSERT INTO lib VALUES (39,'Chris Turnera','CB','6-3',175,'SO','Columbia','SC');
INSERT INTO lib VALUES (40,'Zac Foutza','TE','6-4',250,'FR','Roanoke','VA');
INSERT INTO lib VALUES (42,'Erwin Dessourcesa','DE','6-1',235,'SR','Randolph','MA');
INSERT INTO lib VALUES (43,'Benjamin Alexandera','S','6-2',175,'FR','Spring Mills','PA');
INSERT INTO lib VALUES (44,'Dia''Vante Browna','DE','6-2',245,'JR','Greensboro','NC');
INSERT INTO lib VALUES (47,'Ben Thomasa','DL','6-2',245,'JR','Greenwood','SC');
INSERT INTO lib VALUES (48,'David Kinga','LB','6-1',230,'SO','Stuarts Draft','VA');
INSERT INTO lib VALUES (49,'Jason Pittsa','LB','6-0',200,'JR','Detroit','MI');
INSERT INTO lib VALUES (51,'Trystin Knowlanda','OL','6-6',275,'FR','Manchester','CT');
INSERT INTO lib VALUES (52,'Michael Andersona','DE','6-3',220,'FR','Fort Lauderdale','FL');
INSERT INTO lib VALUES (53,'Joshua Carlina','OL','6-3',245,'FR','Forest','VA');
INSERT INTO lib VALUES (54,'Juwan Wellsa','DE','6-2',255,'SO','Dublin','GA');
INSERT INTO lib VALUES (55,'Tolen Averya','DE','6-4',270,'SO','Galveston','TX');
INSERT INTO lib VALUES (56,'Dontae Duffa','OL','6-1',310,'FR','Mesquite','TX');
INSERT INTO lib VALUES (57,'Hunter Winsteada','LS','6-0',240,'JR','Raleigh','NC');
INSERT INTO lib VALUES (59,'Damian Boundsa','OL','6-2',260,'FR','Ellenwood','GA');
INSERT INTO lib VALUES (63,'Aidan Burroughsa','OL','6-3',275,'FR','Norfolk','NE');
INSERT INTO lib VALUES (65,'Thomas Sargeanta','OL','6-3',270,'FR','Mechanicsville','VA');
INSERT INTO lib VALUES (66,'Ethan Crawforda','OL','6-3',295,'FR','Augusta','GA');
INSERT INTO lib VALUES (67,'Michael Hendermana','OL','6-3',300,'JR','Atlanta','GA');
INSERT INTO lib VALUES (68,'Tanner Hartmana','OL','6-4',280,'JR','Christiansburg','VA');
INSERT INTO lib VALUES (69,'Devin Crispa','OL','6-1',295,'SR','Oklahoma City','OK');
INSERT INTO lib VALUES (70,'Lucas Holdera','OL','6-4',295,'JR','Hillsville','VA');
INSERT INTO lib VALUES (73,'Sam Isaacsona','OL','6-6',305,'FR','Lynchburg','VA');
INSERT INTO lib VALUES (74,'Julio Lozanoa','OL','6-4',270,'SO','Bellaire','TX');
INSERT INTO lib VALUES (75,'Gregg Storeya','DL','6-5',345,'SO','Cary','NC');
INSERT INTO lib VALUES (76,'JaRon Greenea','DT','6-2',310,'SR','Beaumont','TX');
INSERT INTO lib VALUES (77,'James Passmorea','OL','6-6',295,'SO','Dallas','NC');
INSERT INTO lib VALUES (77,'Daniel Zapataa','OL','6-2',255,'FR','Guttenberg','NJ');
INSERT INTO lib VALUES (78,'Ernst Andersena','OL','6-7',300,'FR','--','--');
INSERT INTO lib VALUES (79,'Aharown Campbella','OL','6-5',355,'SR','Teaneck','NJ');
INSERT INTO lib VALUES (80,'Joshua Cruza','WR','6-1',185,'FR','Charlotte','NC');
INSERT INTO lib VALUES (81,'Marquis Fitzgeralda','WR','6-1',190,'JR','Farmville','VA');
INSERT INTO lib VALUES (82,'B.J. Farrowa','WR','6-2',190,'SO','Lynchburg','VA');
INSERT INTO lib VALUES (83,'Josh Tullya','WR','5-10',175,'FR','Vancouver','WA');
INSERT INTO lib VALUES (85,'Kyle Carringtona','WR','6-1',190,'FR','Toms River','NJ');
INSERT INTO lib VALUES (87,'Cephas Reddicka','WR','5-8',175,'SO','Woodbridge','VA');
INSERT INTO lib VALUES (88,'Isaac Browna','WR','6-3',190,'JR','Overton','NE');
INSERT INTO lib VALUES (89,'Canon Smitha','TE','6-4',255,'SR','Hoover','AL');
INSERT INTO lib VALUES (90,'Will Browna','DL','6-2',300,'SO','Texarkana','TX');
INSERT INTO lib VALUES (91,'Javon Fraziera','DE','6-2',245,'FR','Stafford','VA');
INSERT INTO lib VALUES (94,'John Roughtona','DE','6-3',225,'JR','--','--');
INSERT INTO lib VALUES (95,'Devin Fishera','DE','6-1',235,'FR','Radford','VA');
INSERT INTO lib VALUES (97,'Aaron Wallera','DT','6-3',365,'SR','Long Beach','CA');
INSERT INTO lib VALUES (99,'Ralfs Rusinsa','TE','6-5',295,'FR','--','--');
