CREATE TABLE Players (
    `No` VARCHAR(2) CHARACTER SET utf8,
    `Name` VARCHAR(23) CHARACTER SET utf8,
    `Pos` VARCHAR(2) CHARACTER SET utf8,
    `Ht` VARCHAR(4) CHARACTER SET utf8,
    `Wt` INT,
    `Class` VARCHAR(2) CHARACTER SET utf8,
    `Hometown` VARCHAR(21) CHARACTER SET utf8,
    `State` VARCHAR(2) CHARACTER SET utf8,
    `Team` VARCHAR(3) CHARACTER SET utf8
);
INSERT INTO Players VALUES ('--','Naji Abdullaha','DE','6-5',235,'FR','Jacksonville','FL','UVA');
INSERT INTO Players VALUES ('--','Sonny Abramsona','QB','6-2',210,'FR','Chester','NJ','UVA');
INSERT INTO Players VALUES ('--','Christian Baumgardnera','DE','6-6',235,'FR','Longport','NJ','UVA');
INSERT INTO Players VALUES ('--','Ethan Blundina','WR','6-3',190,'FR','Charlottesville','VA','UVA');
INSERT INTO Players VALUES ('--','Christian Brooksa','DL','6-5',240,'FR','Centreville','VA','UVA');
INSERT INTO Players VALUES ('--','Dre Bryanta','LB','6-3',220,'FR','Charlottesville','VA','UVA');
INSERT INTO Players VALUES ('--','De''Vante Crossa','QB','6-2',200,'FR','Allentown','PA','UVA');
INSERT INTO Players VALUES ('--','Osiris Crutchfielda','DL','6-3',245,'FR','Crozet','VA','UVA');
INSERT INTO Players VALUES ('--','Chuck Davisa','CB','5-10',170,'FR','Fairfax','VA','UVA');
INSERT INTO Players VALUES ('--','Dillon Davisa','LB','6-2',210,'FR','Bellaire','TX','UVA');
INSERT INTO Players VALUES ('--','CJ Eppsa','S','5-11',195,'FR','Chesapeake','VA','UVA');
INSERT INTO Players VALUES ('--','Nick Granta','DB','6-3',185,'FR','Spotsylvania','VA','UVA');
INSERT INTO Players VALUES ('--','Nash Griffina','PK','6-4',215,'FR','Indianapolis','IN','UVA');
INSERT INTO Players VALUES ('--','Michael Guercia','LB','6-2',220,'SO','Franklin Lakes','NJ','UVA');
INSERT INTO Players VALUES ('--','Trenton Jenkinsa','OT','6-6',280,'FR','Charlottesville','VA','UVA');
INSERT INTO Players VALUES ('--','Patrick Kidda','G','6-4',290,'SO','Woodbridge','VA','UVA');
INSERT INTO Players VALUES ('--','Darious Latimorea','CB','6-0',170,'SO','Lawrenceville','GA','UVA');
INSERT INTO Players VALUES ('--','Dylan Lea','WR','5-7',165,'SO','Ashburn','VA','UVA');
INSERT INTO Players VALUES ('--','Brenton Nelsona','S','5-11',170,'FR','Miami','FL','UVA');
INSERT INTO Players VALUES ('--','Dillon Reinkensmeyera','OL','6-6',275,'FR','Highlands Ranch','CO','UVA');
INSERT INTO Players VALUES ('--','Dominic Shepparda','LB','6-2',220,'FR','Miami','FL','UVA');
INSERT INTO Players VALUES ('--','Alec Shiffletta','DL','6-2',220,'JR','Afton','VA','UVA');
INSERT INTO Players VALUES ('--','Tyler Shirleya','LS','6-3',220,'JR','Midlothian','VA','UVA');
INSERT INTO Players VALUES ('--','Ben Trenta','OT','6-7',290,'FR','Forest','VA','UVA');
INSERT INTO Players VALUES ('--','Rambert Tyreea','WR','6-0',175,'SO','Newport News','VA','UVA');
INSERT INTO Players VALUES ('1','Donte Wilkinsa','DT','6-1',300,'SR','Woodbridge','VA','UVA');
INSERT INTO Players VALUES ('2','Albert Reida','RB','5-9',215,'SR','Washington','DC','UVA');
INSERT INTO Players VALUES ('3','Quin Blandinga','S','6-2',215,'JR','Virginia Beach','VA','UVA');
INSERT INTO Players VALUES ('4','Taquan Mizzella','RB','5-10',195,'SR','Virginia Beach','VA','UVA');
INSERT INTO Players VALUES ('5','Tim Harrisa','CB','6-2',205,'SR','Richmond','VA','UVA');
INSERT INTO Players VALUES ('5','Jamil Kamaraa','WR','6-2',205,'SO','Virginia Beach','VA','UVA');
INSERT INTO Players VALUES ('6','Kurt Benkerta','QB','6-4',230,'JR','Cape Coral','FL','UVA');
INSERT INTO Players VALUES ('7','Doni Dowlinga','WR','6-1',215,'JR','Richmond','VA','UVA');
INSERT INTO Players VALUES ('8','Keeon Johnsona','WR','6-3',215,'SR','Kannapolis','NC','UVA');
INSERT INTO Players VALUES ('9','Andrew Browna','DE','6-4',290,'JR','Chesapeake','VA','UVA');
INSERT INTO Players VALUES ('10','Jordan Ellisa','RB','5-11',220,'SO','Suwanee','GA','UVA');
INSERT INTO Players VALUES ('11','David Eldridgea','WR','6-1',180,'SO','Bealeton','VA','UVA');
INSERT INTO Players VALUES ('13','Chris Peacea','LB','6-1',230,'SO','Newport News','VA','UVA');
INSERT INTO Players VALUES ('14','Myles Robinsona','CB','5-11',195,'SO','Olney','MD','UVA');
INSERT INTO Players VALUES ('15','Matt Johnsa','QB','6-5',215,'SR','Chalfont','PA','UVA');
INSERT INTO Players VALUES ('16','Connor Brewera','QB','6-2',195,'SR','Scottsdale','AZ','UVA');
INSERT INTO Players VALUES ('17','Malcolm Cooka','LB','6-1',220,'JR','Richmond','VA','UVA');
INSERT INTO Players VALUES ('18','Ben Hogga','WR','6-0',170,'SO','Lynchburg','VA','UVA');
INSERT INTO Players VALUES ('19','Andre Levronea','WR','6-3',225,'JR','Laurel','MD','UVA');
INSERT INTO Players VALUES ('20','Steven Wrighta','DE','6-4',255,'FR','Waycross','GA','UVA');
INSERT INTO Players VALUES ('21','Juan Thornhilla','S','6-1',190,'SO','Altavista','VA','UVA');
INSERT INTO Players VALUES ('22','Daniel Hamma','RB','5-10',200,'JR','Wytheville','VA','UVA');
INSERT INTO Players VALUES ('23','Warren Crafta','WR','6-2',195,'FR','Roanoke','VA','UVA');
INSERT INTO Players VALUES ('25','Chris Sharpa','S','6-2',195,'FR','Princeton','NJ','UVA');
INSERT INTO Players VALUES ('26','Anthony Callowaya','WR','5-8',160,'JR','Lynchburg','VA','UVA');
INSERT INTO Players VALUES ('27','Cory Jonesa','LB','6-5',220,'SO','Washington','DC','UVA');
INSERT INTO Players VALUES ('28','Wilfred Waheea','S','5-10',200,'SR','Norfolk','VA','UVA');
INSERT INTO Players VALUES ('29','Eric Gallona','LB','6-2',220,'SO','Lakeland','FL','UVA');
INSERT INTO Players VALUES ('30','Nicholas Contea','P','6-3',225,'SR','Roanoke','VA','UVA');
INSERT INTO Players VALUES ('31','Kareem Gibsona','CB','5-11',170,'FR','Johnstown','PA','UVA');
INSERT INTO Players VALUES ('32','Kirk Garnera','CB','5-11',180,'JR','Baltimore','MD','UVA');
INSERT INTO Players VALUES ('33','Olamide Zaccheausa','WR','5-8',190,'SO','Philadelphia','PA','UVA');
INSERT INTO Players VALUES ('34','Bryce Halla','DB','6-3',200,'FR','Harrisburg','PA','UVA');
INSERT INTO Players VALUES ('36','Gladimir Paula','LB','6-2',215,'FR','Philadelphia','PA','UVA');
INSERT INTO Players VALUES ('37','Jordan Macka','DB','6-4',205,'FR','Lithonia','GA','UVA');
INSERT INTO Players VALUES ('38','Kelvin Raineya','S','6-1',205,'SR','Houston','TX','UVA');
INSERT INTO Players VALUES ('39','Chris Moorea','DB','6-2',200,'FR','Ashburn','VA','UVA');
INSERT INTO Players VALUES ('40','C.J. Stalkera','LB','6-2',225,'SO','West Chester','OH','UVA');
INSERT INTO Players VALUES ('41','Connor Wingo-Reevesa','FB','6-3',225,'SR','Midlothian','VA','UVA');
INSERT INTO Players VALUES ('42','Jahvoni Simmonsa','LB','6-1',225,'FR','Virginia Beach','VA','UVA');
INSERT INTO Players VALUES ('43','Sean Fitzgeralda','LB','5-11',225,'FR','Falls Church','VA','UVA');
INSERT INTO Players VALUES ('44','Tanner Cowleya','WR','6-4',220,'FR','Manasquan','NJ','UVA');
INSERT INTO Players VALUES ('45','Reed Kellama','LB','6-1',225,'FR','Richmond','VA','UVA');
INSERT INTO Players VALUES ('46','Evan Buttsa','TE','6-4',245,'SO','Newtown Square','PA','UVA');
INSERT INTO Players VALUES ('47','Lester Colemana','P','6-5',225,'SO','Martinsville','VA','UVA');
INSERT INTO Players VALUES ('50','Jackson Matteoa','C','6-5',290,'SR','Ashburn','VA','UVA');
INSERT INTO Players VALUES ('51','Zach Bradshawa','LB','6-3',230,'SR','Damascus','MD','UVA');
INSERT INTO Players VALUES ('52','Robert Snydera','LB','6-4',220,'FR','Lawrenceville','GA','UVA');
INSERT INTO Players VALUES ('53','Micah Kisera','LB','6-2',240,'JR','Baltimore','MD','UVA');
INSERT INTO Players VALUES ('54','Matt Terrella','LB','6-4',225,'FR','Lynchburg','VA','UVA');
INSERT INTO Players VALUES ('56','Andre Miles-Redmonda','DT','6-4',275,'SR','Richmond','VA','UVA');
INSERT INTO Players VALUES ('57','James Trucillaa','DT','6-1',270,'FR','Erie','PA','UVA');
INSERT INTO Players VALUES ('58','Eli Hanbacka','DE','6-4',270,'FR','Ashland','VA','UVA');
INSERT INTO Players VALUES ('59','Mark Halla','DE','6-2',260,'SR','Virginia Beach','VA','UVA');
INSERT INTO Players VALUES ('62','Sean Karla','G','6-6',300,'SR','Manorville','NY','UVA');
INSERT INTO Players VALUES ('65','Ben Knutsona','OL','6-9',310,'FR','Granger','IN','UVA');
INSERT INTO Players VALUES ('67','Jack Englisha','OT','6-5',290,'JR','Richmond','VA','UVA');
INSERT INTO Players VALUES ('70','Steven Mossa','G','6-4',300,'SO','Fredericksburg','VA','UVA');
INSERT INTO Players VALUES ('71','Jack McDonalda','G','6-5',290,'JR','Quincy','MA','UVA');
INSERT INTO Players VALUES ('72','Eric Smitha','OT','6-5',300,'SR','Decatur','GA','UVA');
INSERT INTO Players VALUES ('74','Ryan Bischoffa','OT','6-6',290,'FR','Plymouth','PA','UVA');
INSERT INTO Players VALUES ('76','Michael Mooneya','OT','6-6',295,'SR','Malvern','PA','UVA');
INSERT INTO Players VALUES ('77','Jake Fielera','OT','6-5',300,'SO','Parkersburg','WV','UVA');
INSERT INTO Players VALUES ('78','R.J. Proctora','C','6-5',305,'FR','Bealeton','VA','UVA');
INSERT INTO Players VALUES ('80','Hasise Duboisa','WR','6-3',210,'FR','Irvington','NJ','UVA');
INSERT INTO Players VALUES ('81','Joe Reeda','WR','6-3',210,'FR','Charlotte Court House','VA','UVA');
INSERT INTO Players VALUES ('82','Braedon Uriea','WR','5-10',175,'SO','Purcellville','VA','UVA');
INSERT INTO Players VALUES ('83','Brendan Marshalla','TE','6-5',235,'JR','Gaithersburg','MD','UVA');
INSERT INTO Players VALUES ('84','Alex Furbanka','PK','6-0',220,'SO','Fairfax','VA','UVA');
INSERT INTO Players VALUES ('85','Cole Blackmana','WR','6-1',195,'FR','Glen Allen','VA','UVA');
INSERT INTO Players VALUES ('86','Ross Gardnera','WR','6-3',210,'SO','Mechanicsville','VA','UVA');
INSERT INTO Players VALUES ('87','Richard Burneya','TE','6-4',245,'FR','Chesapeake','VA','UVA');
INSERT INTO Players VALUES ('88','Ryan Santoroa','WR','6-2',215,'SR','Oak Hill','VA','UVA');
INSERT INTO Players VALUES ('89','Sam Haywarda','PK','6-0',165,'JR','Dallas','TX','UVA');
INSERT INTO Players VALUES ('90','Jack Powersa','DE','6-5',280,'JR','Santa Cruz','CA','UVA');
INSERT INTO Players VALUES ('91','Dylan Simsa','PK','6-0',190,'SR','Lynchburg','VA','UVA');
INSERT INTO Players VALUES ('95','Juwan Moyea','LB','6-3',255,'FR','Lilburn','GA','UVA');
INSERT INTO Players VALUES ('98','Landan Worda','LB','6-5',245,'FR','Vienna','VA','UVA');
INSERT INTO Players VALUES ('99','Joe Spaziania','QB','6-2',210,'SO','Hingham','MA','UVA');
INSERT INTO Players VALUES ('1','Isaiah Forda','WR','6-2',190,'JR','Jacksonville','FL','VT');
INSERT INTO Players VALUES ('2','Tyree Rodgersa','DB','6-1',180,'FR','Camden','NJ','VT');
INSERT INTO Players VALUES ('3','Greg Stromana','DB','6-1',170,'JR','Bristow','VA','VT');
INSERT INTO Players VALUES ('4','Ken Ekanema','DE','6-3',253,'SR','Centreville','VA','VT');
INSERT INTO Players VALUES ('4','Jerod Evansa','QB','6-4',235,'JR','Dallas','TX','VT');
INSERT INTO Players VALUES ('5','Cam Phillipsa','WR','6-1',198,'JR','Laurel','MD','VT');
INSERT INTO Players VALUES ('6','Mook Reynoldsa','S','6-1',184,'SO','Greensboro','NC','VT');
INSERT INTO Players VALUES ('7','Bucky Hodgesa','TE','6-7',245,'JR','Virginia Beach','VA','VT');
INSERT INTO Players VALUES ('8','Phil Pattersona','WR','6-2',185,'FR','Virginia Beach','VA','VT');
INSERT INTO Players VALUES ('8','Nigel Williamsa','DT','6-4',295,'SR','Richmond','VA','VT');
INSERT INTO Players VALUES ('9','Khalil Ladlera','CB','5-11',178,'FR','Stone Mountain','GA','VT');
INSERT INTO Players VALUES ('9','Brenden Motleya','QB','6-3',225,'SR','Christiansburg','VA','VT');
INSERT INTO Players VALUES ('11','Jack Clicka','QB','6-3',216,'FR','Glen Allen','VA','VT');
INSERT INTO Players VALUES ('11','Houshun Gainesa','DE','6-4',231,'FR','Rocky Mount','NC','VT');
INSERT INTO Players VALUES ('12','Josh Jacksona','QB','6-2',207,'FR','Ann Arbor','MI','VT');
INSERT INTO Players VALUES ('12','Henri Murphya','WR','5-11',185,'JR','White Hall','AR','VT');
INSERT INTO Players VALUES ('13','Chris Durkina','TE','6-4',232,'SO','Poland','OH','VT');
INSERT INTO Players VALUES ('14','Tavante Becketta','LB','6-0',215,'FR','Chesapeake','VA','VT');
INSERT INTO Players VALUES ('15','Jaylen Bradshawa','WR','6-1',198,'SO','Chesapeake','VA','VT');
INSERT INTO Players VALUES ('16','Coleman Foxa','RB','5-11',192,'FR','Salem','VA','VT');
INSERT INTO Players VALUES ('17','Jahque Alleynea','S','6-1',175,'SO','Virginia Beach','VA','VT');
INSERT INTO Players VALUES ('18','Raymon Minora','LB','6-2',231,'SO','Ashland','VA','VT');
INSERT INTO Players VALUES ('18','Chase Mummaua','QB','6-2',174,'FR','Mechanicsville','VA','VT');
INSERT INTO Players VALUES ('19','Chuck Clarka','S','6-1',202,'SR','Suffolk','VA','VT');
INSERT INTO Players VALUES ('20','Deon Newsomea','S','5-11',187,'JR','Hampton','VA','VT');
INSERT INTO Players VALUES ('21','Reggie Floyda','DB','6-0',200,'FR','Manassas','VA','VT');
INSERT INTO Players VALUES ('22','Terrell Edmundsa','LB','6-1',201,'SO','Danville','VA','VT');
INSERT INTO Players VALUES ('23','Der''Woun Greenea','S','5-11',194,'SR','Portsmouth','VA','VT');
INSERT INTO Players VALUES ('24','Anthony Shegoga','LB','6-3',212,'JR','Stafford','VA','VT');
INSERT INTO Players VALUES ('26','Jovonn Quillena','DB','6-2',195,'FR','Hampton','VA','VT');
INSERT INTO Players VALUES ('27','Dominic Bensona','WR','6-1',176,'FR','Woodbridge','VA','VT');
INSERT INTO Players VALUES ('27','Shawn Paynea','CB','6-3',185,'SO','Chesterfield','VA','VT');
INSERT INTO Players VALUES ('28','Shai McKenziea','RB','5-11',215,'SO','Washington','PA','VT');
INSERT INTO Players VALUES ('28','Curtis Williamsa','CB','5-9',176,'JR','Amelia','VA','VT');
INSERT INTO Players VALUES ('29','DuWayne Johnsona','CB','6-2',180,'FR','Washington','DC','VT');
INSERT INTO Players VALUES ('30','Eron Cartera','LB','6-2',230,'FR','Palatka','FL','VT');
INSERT INTO Players VALUES ('30','Jordan Jeffersona','WR','5-10',168,'FR','Goochland','VA','VT');
INSERT INTO Players VALUES ('31','Brandon Facysona','CB','6-2',191,'JR','Newnan','GA','VT');
INSERT INTO Players VALUES ('32','Steven Peoplesa','FB','5-9',218,'SO','Galax','VA','VT');
INSERT INTO Players VALUES ('33','Deshawn McCleasea','RB','5-9',177,'FR','Chesapeake','VA','VT');
INSERT INTO Players VALUES ('34','Travon McMilliana','RB','6-0',200,'SO','Woodbridge','VA','VT');
INSERT INTO Players VALUES ('35','Erikk Banksa','CB','5-10',173,'JR','Coeburn','VA','VT');
INSERT INTO Players VALUES ('35','Michael Santamariaa','PK','5-8',168,'SO','Athens','GA','VT');
INSERT INTO Players VALUES ('36','Adonis Alexandera','CB','6-3',197,'SO','Charlotte','NC','VT');
INSERT INTO Players VALUES ('36','Alden Carpentera','LB','6-1',192,'JR','Leesburg','VA','VT');
INSERT INTO Players VALUES ('37','Johnathan Galantea','LB','5-9',210,'SR','Blacksburg','VA','VT');
INSERT INTO Players VALUES ('39','Sean Daniela','WR','5-10',175,'FR','Chesapeake','VA','VT');
INSERT INTO Players VALUES ('39','Tyrone Thorntona','DB','5-10',190,'FR','Boston','MA','VT');
INSERT INTO Players VALUES ('40','Emmanuel Belmara','LB','6-2',230,'FR','Suwanee','GA','VT');
INSERT INTO Players VALUES ('41','Kevin Henrya','WR','6-0',170,'FR','Greensboro','NC','VT');
INSERT INTO Players VALUES ('41','John Jenningsa','DB','5-11',165,'SO','Clifton','VA','VT');
INSERT INTO Players VALUES ('41','Trey Skeensa','FB','6-0',215,'FR','Wytheville','VA','VT');
INSERT INTO Players VALUES ('42','Elisha Boyda','CB','6-0',175,'SO','Newport News','VA','VT');
INSERT INTO Players VALUES ('42','Marshawn Williamsa','RB','5-11',239,'SO','Hampton','VA','VT');
INSERT INTO Players VALUES ('43','Seth Dooleya','DE','6-6',239,'JR','Salem','VA','VT');
INSERT INTO Players VALUES ('44','Tre Hubbarda','LB','6-0',230,'FR','Virginia Beach','VA','VT');
INSERT INTO Players VALUES ('45','Sam Rogersa','FB','5-10',227,'SR','Mechanicsville','VA','VT');
INSERT INTO Players VALUES ('46','Joey Slyea','PK','6-1',207,'JR','Stafford','VA','VT');
INSERT INTO Players VALUES ('47','Darius Fullwooda','DE','6-4',262,'FR','College Park','MD','VT');
INSERT INTO Players VALUES ('48','Daniel Griffitha','LB','6-1',225,'FR','Suffolk','VA','VT');
INSERT INTO Players VALUES ('48','D.J. Reida','RB','6-1',240,'SO','Chester','VA','VT');
INSERT INTO Players VALUES ('49','Tremaine Edmundsa','LB','6-5',236,'SO','Danville','VA','VT');
INSERT INTO Players VALUES ('50','Patrick Kearnsa','OL','6-5',280,'FR','Adairsville','GA','VT');
INSERT INTO Players VALUES ('51','Hundley McCurrya','LS','5-11',190,'FR','Summerville','SC','VT');
INSERT INTO Players VALUES ('52','Austin Cannona','OL','6-3',315,'FR','Mechanicsville','VA','VT');
INSERT INTO Players VALUES ('52','Clay Deana','DL','6-2',255,'FR','Purcellville','VA','VT');
INSERT INTO Players VALUES ('53','Wayne Muttera','P','5-9',160,'SR','Grundy','VA','VT');
INSERT INTO Players VALUES ('53','Trent Younga','LB','5-10',212,'SO','Richmond','VA','VT');
INSERT INTO Players VALUES ('54','Andrew Motuapuakaa','LB','6-0',235,'JR','Virginia Beach','VA','VT');
INSERT INTO Players VALUES ('55','Jarrod Hewitta','DL','6-1',290,'FR','Venice','FL','VT');
INSERT INTO Players VALUES ('56','Sean Huelskampa','LB','6-1',207,'JR','Centreville','VA','VT');
INSERT INTO Players VALUES ('56','T.J. Jacksona','OL','6-3',330,'FR','Cumberland','VA','VT');
INSERT INTO Players VALUES ('57','Wyatt Tellera','OL','6-5',304,'JR','Bealeton','VA','VT');
INSERT INTO Players VALUES ('58','Zack Tresera','LB','6-4',221,'FR','Blacksburg','VA','VT');
INSERT INTO Players VALUES ('60','Woody Barona','DT','6-1',275,'SR','Nashville','TN','VT');
INSERT INTO Players VALUES ('61','Kyle Chunga','OL','6-4',290,'JR','Ponte Vedra Beach','FL','VT');
INSERT INTO Players VALUES ('61','Joe Koshutaa','LB','6-2',240,'FR','Vienna','VA','VT');
INSERT INTO Players VALUES ('62','D''Andre Plantina','OL','6-5',290,'FR','Norcross','GA','VT');
INSERT INTO Players VALUES ('63','Daniel Baileya','OL','6-4',296,'FR','Abingdon','VA','VT');
INSERT INTO Players VALUES ('64','Eric Galloa','OL','6-2',297,'JR','Richboro','PA','VT');
INSERT INTO Players VALUES ('65','Matt Christa','OL','6-4',274,'FR','Sterling','VA','VT');
INSERT INTO Players VALUES ('66','Billy Mitchella','OL','6-3',284,'SO','Westwood','NJ','VT');
INSERT INTO Players VALUES ('67','Parker Osterloha','OL','6-8',336,'JR','Williamsburg','VA','VT');
INSERT INTO Players VALUES ('68','Connor Kisha','OL','6-2',280,'FR','Oceanside','CA','VT');
INSERT INTO Players VALUES ('69','Yosuah Nijmana','OL','6-8',298,'SO','Maplewood','NJ','VT');
INSERT INTO Players VALUES ('70','Kevin Kisha','OL','6-2',280,'FR','Oceanside','CA','VT');
INSERT INTO Players VALUES ('71','Jonathan McLaughlina','OL','6-5',300,'SR','Mauldin','SC','VT');
INSERT INTO Players VALUES ('72','Augie Contea','OL','6-6',303,'SR','Richmond','VA','VT');
INSERT INTO Players VALUES ('74','Braxton Pfaffa','OL','6-5',295,'SO','Lynchburg','VA','VT');
INSERT INTO Players VALUES ('75','Zachariah Hoyta','OL','6-5',286,'FR','Salem','VA','VT');
INSERT INTO Players VALUES ('76','Jarrett Hopplea','OL','6-6',280,'FR','Suffolk','VA','VT');
INSERT INTO Players VALUES ('77','Demetri Moorea','OL','6-5',305,'JR','Fairborn','OH','VT');
INSERT INTO Players VALUES ('79','Tyrell Smitha','OL','6-3',292,'FR','North Brunswick','NJ','VT');
INSERT INTO Players VALUES ('80','Casey Harmana','TE','6-4',240,'FR','Swords Creek','VA','VT');
INSERT INTO Players VALUES ('80','Colt Pettita','OL','6-4',298,'SO','Deshler','OH','VT');
INSERT INTO Players VALUES ('81','Samuel Denmarka','WR','6-0',182,'FR','Hanahan','SC','VT');
INSERT INTO Players VALUES ('82','Xavier Burkea','TE','6-2',270,'FR','Lawrenceville','VA','VT');
INSERT INTO Players VALUES ('83','Eric Kumaha','WR','6-2',203,'FR','Woodbridge','VA','VT');
INSERT INTO Players VALUES ('85','Chris Cunninghama','TE','6-2',242,'FR','Jacksonville','FL','VT');
INSERT INTO Players VALUES ('86','C.J. Carrolla','WR','5-7',165,'SO','Olney','MD','VT');
INSERT INTO Players VALUES ('87','Bodhie Longa','WR','6-3',200,'FR','Richmond','VA','VT');
INSERT INTO Players VALUES ('87','Colton Taylora','LS','6-1',212,'JR','Salem','VA','VT');
INSERT INTO Players VALUES ('88','Divine Deabloa','WR','6-3',210,'FR','Winston-salem','NC','VT');
INSERT INTO Players VALUES ('89','Wright Bynuma','LS','6-4',230,'FR','Columbia','SC','VT');
INSERT INTO Players VALUES ('89','Devin Wilsona','WR','6-4',190,'JR','Mckees Rocks','PA','VT');
INSERT INTO Players VALUES ('90','Mitchell Ludwiga','P','5-11',200,'JR','Abingdon','VA','VT');
INSERT INTO Players VALUES ('90','Dalton Roea','DT','6-1',235,'JR','Williamsburg','VA','VT');
INSERT INTO Players VALUES ('91','Steve Sobczaka','DT','6-1',300,'SO','Milford','VA','VT');
INSERT INTO Players VALUES ('92','Matt Reinharta','LB','6-2',225,'FR','Shoemakersville','PA','VT');
INSERT INTO Players VALUES ('92','Robert Warfela','PK','5-10',164,'SR','--','--','VT');
INSERT INTO Players VALUES ('93','Brian Johnsona','P','6-1',161,'FR','Washington','DC','VT');
INSERT INTO Players VALUES ('94','Trevon Hilla','DE','6-5',234,'FR','Virginia Beach','VA','VT');
INSERT INTO Players VALUES ('95','Chaska Moona','LS','6-0',249,'FR','Wake Forest','NC','VT');
INSERT INTO Players VALUES ('96','Jimmie Taylora','DE','6-3',225,'FR','Jacksonville','NC','VT');
INSERT INTO Players VALUES ('97','Tim Settlea','DT','6-3',344,'FR','Manassas','VA','VT');
INSERT INTO Players VALUES ('98','Ricky Walkera','DT','6-2',288,'SO','Hampton','VA','VT');
INSERT INTO Players VALUES ('99','Vinny Mihotaa','DL','6-5',270,'SO','Fredericksburg','VA','VT');
INSERT INTO Players VALUES ('1','DeCarlo Hamiltona','DT','6-3',335,'FR','Plantation','FL','Lib');
INSERT INTO Players VALUES ('1','Zac Parkera','WR','5-9',185,'SR','Reston','VA','Lib');
INSERT INTO Players VALUES ('2','Jeremy Petersa','CB','5-10',190,'SO','Green Cove Springs','FL','Lib');
INSERT INTO Players VALUES ('3','Rion Davisa','S','6-0',190,'FR','Hopkins','SC','Lib');
INSERT INTO Players VALUES ('3','Stephon Mashaa','QB','6-1',205,'JR','Marietta','GA','Lib');
INSERT INTO Players VALUES ('4','Jaylyn McKinneya','LB','6-0',225,'FR','Lake Wales','FL','Lib');
INSERT INTO Players VALUES ('5','Lucas Ironsa','LB','6-0',215,'SO','Fort Lauderdale','FL','Lib');
INSERT INTO Players VALUES ('6','Tyrin Hollowaya','CB','6-0',195,'JR','Humble','TX','Lib');
INSERT INTO Players VALUES ('7','Ceneca Espinoza Jr.a','S','6-1',200,'FR','Arlington','VA','Lib');
INSERT INTO Players VALUES ('7','Damian Kinga','WR','5-11',175,'SO','--','--','Lib');
INSERT INTO Players VALUES ('8','Jimmy Faulksa','CB','6-1',175,'FR','--','--','Lib');
INSERT INTO Players VALUES ('8','Dante Shellsa','WR','6-1',180,'SR','Camden','DE','Lib');
INSERT INTO Players VALUES ('9','Nick Newmana','LB','6-4',215,'SR','Gainesville','VA','Lib');
INSERT INTO Players VALUES ('10','Alex Proberta','PK','5-9',170,'FR','Andover','MN','Lib');
INSERT INTO Players VALUES ('11','Antonio Gandy-Goldena','WR','6-4',200,'FR','Dallas','GA','Lib');
INSERT INTO Players VALUES ('11','Cole Gibsona','PK','6-1',235,'FR','Chesapeake','VA','Lib');
INSERT INTO Players VALUES ('11','Lionell McConnella','WR','5-10',180,'FR','Allen','TX','Lib');
INSERT INTO Players VALUES ('12','Stephen Calverta','QB','6-2',180,'FR','Plantation','FL','Lib');
INSERT INTO Players VALUES ('12','Brandon Tillmona','S','6-1',210,'FR','Lexington','SC','Lib');
INSERT INTO Players VALUES ('13','Korell Evansa','LB','6-1',215,'FR','Hallandale','FL','Lib');
INSERT INTO Players VALUES ('13','Rudiger Yearicka','QB','6-3',195,'FR','Matthews','NC','Lib');
INSERT INTO Players VALUES ('14','Cam Jacksona','CB','6-1',205,'SO','Houston','TX','Lib');
INSERT INTO Players VALUES ('15','T.J. Tillerya','CB','5-10',195,'SO','Charlottesville','VA','Lib');
INSERT INTO Players VALUES ('16','Spencer Jonesa','QB','6-3',185,'FR','Nashville','TN','Lib');
INSERT INTO Players VALUES ('17','Kendall Couamina','TE','6-2',255,'JR','Miami Lakes','FL','Lib');
INSERT INTO Players VALUES ('18','Josh Newmana','WR','5-10',190,'FR','Gainesville','VA','Lib');
INSERT INTO Players VALUES ('19','Will Johnsona','TE','6-6',265,'SR','Osseo','MN','Lib');
INSERT INTO Players VALUES ('20','Solomon McGintya','S','6-2',220,'JR','Navasota','TX','Lib');
INSERT INTO Players VALUES ('21','Mitchell Lewisa','RB','6-0',220,'FR','Auburn','AL','Lib');
INSERT INTO Players VALUES ('21','Wesley Scotta','CB','5-10',175,'SR','Lorton','VA','Lib');
INSERT INTO Players VALUES ('22','Todd Macona','RB','5-10',210,'JR','--','--','Lib');
INSERT INTO Players VALUES ('23','Frankie Hicksona','RB','5-8',200,'FR','Lynchburg','VA','Lib');
INSERT INTO Players VALUES ('24','Malik Matthewsa','CB','5-11',185,'FR','Jacksonville','FL','Lib');
INSERT INTO Players VALUES ('25','Aaron Glovera','LB','5-11',210,'FR','Norfolk','VA','Lib');
INSERT INTO Players VALUES ('26','Joseph Dixona','RB','5-9',190,'SO','--','--','Lib');
INSERT INTO Players VALUES ('27','Cameron Jonesa','CB','5-11',195,'SO','New Orleans','LA','Lib');
INSERT INTO Players VALUES ('28','Corbin Jacksona','S','6-0',200,'SO','Charlotte','NC','Lib');
INSERT INTO Players VALUES ('29','David Jeremaiha','WR','0-0',0,'FR','--','--','Lib');
INSERT INTO Players VALUES ('30','Dexter Robbinsa','LB','5-11',225,'SR','Sevierville','TN','Lib');
INSERT INTO Players VALUES ('31','Elijah Bentona','S','6-1',190,'FR','Forest','VA','Lib');
INSERT INTO Players VALUES ('32','Jermaine Copelanda','CB','5-9',190,'FR','Farmville','VA','Lib');
INSERT INTO Players VALUES ('33','Didier Monciona','RB','5-8',205,'JR','MANSFIELD','CT','Lib');
INSERT INTO Players VALUES ('34','Carrington Mosleya','RB','5-11',235,'JR','Brookneal','VA','Lib');
INSERT INTO Players VALUES ('35','Trey Turnera','P','5-11',210,'JR','Rome','GA','Lib');
INSERT INTO Players VALUES ('36','Thomas Kennedya','FB','5-11',240,'JR','Roanoke','VA','Lib');
INSERT INTO Players VALUES ('38','Alpha Jalloha','S','6-1',200,'SR','New Carrollton','MD','Lib');
INSERT INTO Players VALUES ('39','Chris Turnera','CB','6-3',175,'SO','Columbia','SC','Lib');
INSERT INTO Players VALUES ('40','Zac Foutza','TE','6-4',250,'FR','Roanoke','VA','Lib');
INSERT INTO Players VALUES ('42','Erwin Dessourcesa','DE','6-1',235,'SR','Randolph','MA','Lib');
INSERT INTO Players VALUES ('43','Benjamin Alexandera','S','6-2',175,'FR','Spring Mills','PA','Lib');
INSERT INTO Players VALUES ('44','Dia''Vante Browna','DE','6-2',245,'JR','Greensboro','NC','Lib');
INSERT INTO Players VALUES ('47','Ben Thomasa','DL','6-2',245,'JR','Greenwood','SC','Lib');
INSERT INTO Players VALUES ('48','David Kinga','LB','6-1',230,'SO','Stuarts Draft','VA','Lib');
INSERT INTO Players VALUES ('49','Jason Pittsa','LB','6-0',200,'JR','Detroit','MI','Lib');
INSERT INTO Players VALUES ('51','Trystin Knowlanda','OL','6-6',275,'FR','Manchester','CT','Lib');
INSERT INTO Players VALUES ('52','Michael Andersona','DE','6-3',220,'FR','Fort Lauderdale','FL','Lib');
INSERT INTO Players VALUES ('53','Joshua Carlina','OL','6-3',245,'FR','Forest','VA','Lib');
INSERT INTO Players VALUES ('54','Juwan Wellsa','DE','6-2',255,'SO','Dublin','GA','Lib');
INSERT INTO Players VALUES ('55','Tolen Averya','DE','6-4',270,'SO','Galveston','TX','Lib');
INSERT INTO Players VALUES ('56','Dontae Duffa','OL','6-1',310,'FR','Mesquite','TX','Lib');
INSERT INTO Players VALUES ('57','Hunter Winsteada','LS','6-0',240,'JR','Raleigh','NC','Lib');
INSERT INTO Players VALUES ('59','Damian Boundsa','OL','6-2',260,'FR','Ellenwood','GA','Lib');
INSERT INTO Players VALUES ('63','Aidan Burroughsa','OL','6-3',275,'FR','Norfolk','NE','Lib');
INSERT INTO Players VALUES ('65','Thomas Sargeanta','OL','6-3',270,'FR','Mechanicsville','VA','Lib');
INSERT INTO Players VALUES ('66','Ethan Crawforda','OL','6-3',295,'FR','Augusta','GA','Lib');
INSERT INTO Players VALUES ('67','Michael Hendermana','OL','6-3',300,'JR','Atlanta','GA','Lib');
INSERT INTO Players VALUES ('68','Tanner Hartmana','OL','6-4',280,'JR','Christiansburg','VA','Lib');
INSERT INTO Players VALUES ('69','Devin Crispa','OL','6-1',295,'SR','Oklahoma City','OK','Lib');
INSERT INTO Players VALUES ('70','Lucas Holdera','OL','6-4',295,'JR','Hillsville','VA','Lib');
INSERT INTO Players VALUES ('73','Sam Isaacsona','OL','6-6',305,'FR','Lynchburg','VA','Lib');
INSERT INTO Players VALUES ('74','Julio Lozanoa','OL','6-4',270,'SO','Bellaire','TX','Lib');
INSERT INTO Players VALUES ('75','Gregg Storeya','DL','6-5',345,'SO','Cary','NC','Lib');
INSERT INTO Players VALUES ('76','JaRon Greenea','DT','6-2',310,'SR','Beaumont','TX','Lib');
INSERT INTO Players VALUES ('77','James Passmorea','OL','6-6',295,'SO','Dallas','NC','Lib');
INSERT INTO Players VALUES ('77','Daniel Zapataa','OL','6-2',255,'FR','Guttenberg','NJ','Lib');
INSERT INTO Players VALUES ('78','Ernst Andersena','OL','6-7',300,'FR','--','--','Lib');
INSERT INTO Players VALUES ('79','Aharown Campbella','OL','6-5',355,'SR','Teaneck','NJ','Lib');
INSERT INTO Players VALUES ('80','Joshua Cruza','WR','6-1',185,'FR','Charlotte','NC','Lib');
INSERT INTO Players VALUES ('81','Marquis Fitzgeralda','WR','6-1',190,'JR','Farmville','VA','Lib');
INSERT INTO Players VALUES ('82','B.J. Farrowa','WR','6-2',190,'SO','Lynchburg','VA','Lib');
INSERT INTO Players VALUES ('83','Josh Tullya','WR','5-10',175,'FR','Vancouver','WA','Lib');
INSERT INTO Players VALUES ('85','Kyle Carringtona','WR','6-1',190,'FR','Toms River','NJ','Lib');
INSERT INTO Players VALUES ('87','Cephas Reddicka','WR','5-8',175,'SO','Woodbridge','VA','Lib');
INSERT INTO Players VALUES ('88','Isaac Browna','WR','6-3',190,'JR','Overton','NE','Lib');
INSERT INTO Players VALUES ('89','Canon Smitha','TE','6-4',255,'SR','Hoover','AL','Lib');
INSERT INTO Players VALUES ('90','Will Browna','DL','6-2',300,'SO','Texarkana','TX','Lib');
INSERT INTO Players VALUES ('91','Javon Fraziera','DE','6-2',245,'FR','Stafford','VA','Lib');
INSERT INTO Players VALUES ('94','John Roughtona','DE','6-3',225,'JR','--','--','Lib');
INSERT INTO Players VALUES ('95','Devin Fishera','DE','6-1',235,'FR','Radford','VA','Lib');
INSERT INTO Players VALUES ('97','Aaron Wallera','DT','6-3',365,'SR','Long Beach','CA','Lib');
INSERT INTO Players VALUES ('99','Ralfs Rusinsa','TE','6-5',295,'FR','--','--','Lib');
INSERT INTO Players VALUES ('2','Donte'' Hayneswortha','DB','5-11',195,'SR','Mechanicsville','VA','nor');
INSERT INTO Players VALUES ('3','Gerard Johnsona','RB','5-9',205,'SR','Richmond','VA','nor');
INSERT INTO Players VALUES ('4','James Churcha','WR','6-1',200,'SR','Virginia Beach','VA','nor');
INSERT INTO Players VALUES ('5','Marcus Taylora','WR','5-8',160,'SO','Highland Springs','VA','nor');
INSERT INTO Players VALUES ('6','Tyre Givers-Wilsona','QB','6-3',200,'FR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('7','Greg Hankersona','QB','6-1',190,'SR','Lauderdale Lakes','FL','nor');
INSERT INTO Players VALUES ('8','Brandon Walkera','DB','6-2',205,'SR','Chester','VA','nor');
INSERT INTO Players VALUES ('9','Harry Freemana','DB','6-1',170,'JR','Norfolk','VA','nor');
INSERT INTO Players VALUES ('10','Sandy Chapmana','DB','5-10',180,'SR','Raleigh','NC','nor');
INSERT INTO Players VALUES ('11','Anthony Smitha','LB','6-1',230,'JR','Norfolk','VA','nor');
INSERT INTO Players VALUES ('12','Terrell Reida','DL','6-2',245,'SR','Washington','DC','nor');
INSERT INTO Players VALUES ('13','Cameron Maroufa','PK','5-9',160,'SR','Woodbridge','VA','nor');
INSERT INTO Players VALUES ('15','Joel Caleba','WR','6-2',210,'SR','Richmond','VA','nor');
INSERT INTO Players VALUES ('16','Kinan Humphreya','WR','5-9',180,'FR','Mcdonough','GA','nor');
INSERT INTO Players VALUES ('17','Rodney Smitha','DL','6-3',235,'SR','Pembroke Pines','FL','nor');
INSERT INTO Players VALUES ('18','Bobby Pricea','DB','6-3',180,'FR','Virginia Beach','VA','nor');
INSERT INTO Players VALUES ('19','Johnathan Spencera','WR','5-11',180,'FR','Apex','NC','nor');
INSERT INTO Players VALUES ('20','Malik Buttsa','RB','5-9',180,'FR','Virginia Beach','VA','nor');
INSERT INTO Players VALUES ('21','George Waheea','WR','6-1',180,'FR','Norfolk','VA','nor');
INSERT INTO Players VALUES ('22','Quintreil Chunga','RB','6-1',220,'SO','Midlothian','VA','nor');
INSERT INTO Players VALUES ('23','Shakeem Copelanda','RB','5-9',205,'JR','Woodbridge','VA','nor');
INSERT INTO Players VALUES ('24','Jay Andersona','DL','6-1',215,'SR','Richmond','VA','nor');
INSERT INTO Players VALUES ('25','D.J. Cooka','WR','6-1',195,'FR','Richmond','VA','nor');
INSERT INTO Players VALUES ('26','Leroy Parkera','DB','6-1',195,'SR','Miami','FL','nor');
INSERT INTO Players VALUES ('27','Aaron Chandlera','DB','5-9',175,'SO','Norfolk','VA','nor');
INSERT INTO Players VALUES ('28','Edwin Leea','DB','6-1',185,'FR','Brooklyn','NY','nor');
INSERT INTO Players VALUES ('29','J.T. Waheea','DB','5-11',170,'FR','Norfolk','VA','nor');
INSERT INTO Players VALUES ('30','Aaron Savagea','RB','5-9',210,'SO','Baltimore','MD','nor');
INSERT INTO Players VALUES ('31','Kyle Archiea','LB','6-1',220,'JR','Virginia Beach','VA','nor');
INSERT INTO Players VALUES ('32','Larry Bishopa','RB','5-11',230,'JR','Roanoke','VA','nor');
INSERT INTO Players VALUES ('33','Joseph Atkinsa','RB','5-10',195,'FR','Virginia Beach','VA','nor');
INSERT INTO Players VALUES ('34','Dimitri McKaya','FB','5-11',235,'SO','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('35','Audrex Harrisa','DB','6-1',190,'JR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('36','Ebenezer Agyemang-Kusia','DB','5-11',185,'SO','Triangle','VA','nor');
INSERT INTO Players VALUES ('37','Hakiem Swanna','DB','5-11',180,'JR','Portsmouth','VA','nor');
INSERT INTO Players VALUES ('38','Thomas Stingera','DB','6-1',150,'JR','Leesburg','VA','nor');
INSERT INTO Players VALUES ('39','Bo Lomaxa','PK','5-11',220,'SO','Hampton','VA','nor');
INSERT INTO Players VALUES ('40','Nigel Chavisa','LB','6-2',220,'FR','Richmond','VA','nor');
INSERT INTO Players VALUES ('41','Hadji Gaylorda','DL','6-3',265,'SO','Norfolk','VA','nor');
INSERT INTO Players VALUES ('43','Roy Adamsa','RB','5-9',195,'SO','Richmond','VA','nor');
INSERT INTO Players VALUES ('44','Conley Smitha','FB','5-11',250,'SR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('45','Jeff Leea','TE','6-3',240,'FR','North Chesterfield','VA','nor');
INSERT INTO Players VALUES ('46','Raynard Revelsa','LB','6-1',235,'SR','Richmond','VA','nor');
INSERT INTO Players VALUES ('47','Damiyan Caldwella','LB','6-1',195,'JR','Norfolk','VA','nor');
INSERT INTO Players VALUES ('48','Tim Flooda','RB','5-9',215,'JR','Newport News','VA','nor');
INSERT INTO Players VALUES ('49','Malik Dixona','DB','5-8',160,'FR','Newport News','VA','nor');
INSERT INTO Players VALUES ('50','Jonathan Okafora','DL','6-2',220,'JR','Woodbridge','VA','nor');
INSERT INTO Players VALUES ('51','Kyron Spellera','LB','6-1',235,'FR','Virginia Beach','VA','nor');
INSERT INTO Players VALUES ('52','Louis Humphreya','OL','6-1',290,'SR','Chester','VA','nor');
INSERT INTO Players VALUES ('54','T.C. Livingstona','LB','6-3',200,'JR','Suffolk','VA','nor');
INSERT INTO Players VALUES ('55','Antwan Whitea','LB','6-1',200,'JR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('56','Cephas Hardena','LB','6-1',215,'FR','Goochland','VA','nor');
INSERT INTO Players VALUES ('57','Lamonte Clarka','OL','6-3',310,'SR','Washington','DC','nor');
INSERT INTO Players VALUES ('58','Daniel Oladimejia','OL','6-2',295,'SR','Upper Marlboro','MD','nor');
INSERT INTO Players VALUES ('59','Jordan Crocketta','OL','6-5',325,'FR','Max Meadows','VA','nor');
INSERT INTO Players VALUES ('60','Wes Jonesa','OL','6-1',270,'SO','Wilmington','DE','nor');
INSERT INTO Players VALUES ('61','Anthonee Moorea','OL','6-2',270,'FR','Buckingham','VA','nor');
INSERT INTO Players VALUES ('62','Dominic Jordana','OL','6-2',280,'FR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('63','Jermaine Sumnera','OL','6-4',270,'FR','Virginia Beach','VA','nor');
INSERT INTO Players VALUES ('65','Craig Rodwella','OL','6-4',270,'FR','Richmond','VA','nor');
INSERT INTO Players VALUES ('66','Taro Lipscomba','OL','6-3',290,'FR','Washington','DC','nor');
INSERT INTO Players VALUES ('69','Jake Mazgajewskia','OL','6-6',290,'JR','Hampton','VA','nor');
INSERT INTO Players VALUES ('70','Deshaywn Middletona','DL','6-2',305,'SO','Winston-salem','NC','nor');
INSERT INTO Players VALUES ('71','Jake O''Sullivana','OL','6-4',290,'FR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('75','Kevin Statona','OL','6-6',320,'FR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('76','Mike Carneya','OL','6-5',340,'FR','Norfolk','VA','nor');
INSERT INTO Players VALUES ('77','Kenneth Kirbya','OL','6-5',275,'FR','Newport News','VA','nor');
INSERT INTO Players VALUES ('79','Josh Culbersona','DL','6-5',285,'FR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('80','Antonio Perrymana','WR','6-2',180,'JR','Jacksonville','FL','nor');
INSERT INTO Players VALUES ('81','Demetreus Ferebeea','TE','6-4',235,'JR','Roanoke','VA','nor');
INSERT INTO Players VALUES ('82','Torian Hendersona','TE','6-4',240,'SR','Silver Spring','MD','nor');
INSERT INTO Players VALUES ('83','Justin Smitha','WR','6-2',165,'FR','Richmond','VA','nor');
INSERT INTO Players VALUES ('84','Chuma Awannaa','WR','6-3',205,'FR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('85','Floyd Jonesa','WR','5-9',170,'SO','Hampton','VA','nor');
INSERT INTO Players VALUES ('86','TreVaughn Sneeda','WR','5-10',185,'FR','Portsmouth','VA','nor');
INSERT INTO Players VALUES ('87','Michael Curtisa','WR','6-1',165,'SO','Newport News','VA','nor');
INSERT INTO Players VALUES ('88','Marcque Ellingtona','WR','6-5',190,'FR','Neptune','NJ','nor');
INSERT INTO Players VALUES ('89','Anthony Williamsa','TE','6-3',210,'FR','Norfolk','VA','nor');
INSERT INTO Players VALUES ('90','Walter Brantleya','DL','6-2',345,'SO','Hampton','VA','nor');
INSERT INTO Players VALUES ('91','James Byersa','LB','6-3',200,'SO','Petersburg','VA','nor');
INSERT INTO Players VALUES ('92','James Chapmana','LB','6-1',225,'FR','Portsmouth','VA','nor');
INSERT INTO Players VALUES ('93','Ray Prosisea','DL','6-1',265,'SR','Petersburg','VA','nor');
INSERT INTO Players VALUES ('94','Josh Bryanta','DL','6-5',265,'FR','Ellicott City','MD','nor');
INSERT INTO Players VALUES ('95','Chris Leea','DL','6-3',280,'JR','Woodbridge','VA','nor');
INSERT INTO Players VALUES ('96','Ian Williamsa','DL','6-2',265,'FR','Richmond','VA','nor');
INSERT INTO Players VALUES ('97','Trey Millsa','DL','6-2',290,'SR','Chesapeake','VA','nor');
INSERT INTO Players VALUES ('98','Cornelius Tylera','DL','6-3',295,'SO','Richmond','VA','nor');
INSERT INTO Players VALUES ('99','Kevin Williamsa','DL','6-4',310,'SR','Bradenton','FL','nor');
