CREATE TABLE teams (
    `NAIA` VARCHAR(11) CHARACTER SET utf8,
    `Bluefield_College` VARCHAR(44) CHARACTER SET utf8,
    `Bluefield` VARCHAR(21) CHARACTER SET utf8
);
INSERT INTO teams VALUES ('NCAA DIII','Shenandoah University','Winchester');
INSERT INTO teams VALUES ('NCAA DI','Virginia Tech University','Blacksburg');
INSERT INTO teams VALUES ('NCAA DI','Liberty University','Lynchburg');
INSERT INTO teams VALUES ('NCAA DI','Norfolk State University','Norfolk');
INSERT INTO teams VALUES ('NCAA DIII','Randolph-Macon College','Ashland');
INSERT INTO teams VALUES ('NCAA DII','Virginia Union University','Richmond');
INSERT INTO teams VALUES ('NCAA DII','University of Virginia&#39;s College at Wise','Wise');
INSERT INTO teams VALUES ('NCAA DIII','Southern Virginia University','Buena Vista');
INSERT INTO teams VALUES ('NAIA','Virginia University of Lynchburg','Lynchburg');
INSERT INTO teams VALUES ('NCAA DI','College of William and Mary','Williamsburg');
INSERT INTO teams VALUES ('NCAA DI','Old Dominion University','Norfolk');
INSERT INTO teams VALUES ('NCAA DII','Virginia State University','Petersburg');
INSERT INTO teams VALUES ('NCAA DI','Hampton University','Hampton');
INSERT INTO teams VALUES ('NCAA DI','Virginia Military Institute','Lexington');
INSERT INTO teams VALUES ('NCAA DI','James Madison University','Harrisonburg');
INSERT INTO teams VALUES ('High School','Hayfield Secondary','Alexandria');
INSERT INTO teams VALUES ('High School','Brentsville District High School','Nokesville');
INSERT INTO teams VALUES ('NCAA DI','University of Richmond','Richmond');
INSERT INTO teams VALUES ('High School','Dinwiddie County High School','Dinwiddie');
INSERT INTO teams VALUES ('NCAA DIII','Emory &amp; Henry College','Meadowview');
INSERT INTO teams VALUES ('High School','Culpeper County High School','Culpeper');
INSERT INTO teams VALUES ('High School','Woodson High School','Fairfax');
INSERT INTO teams VALUES ('NCAA DI','University of Virginia','Charlottesville');
INSERT INTO teams VALUES ('High School','Varina High School','Richmond');
INSERT INTO teams VALUES ('High School','South County High School','Lorton');
INSERT INTO teams VALUES ('High School','Grassfield High School','Chesapeake');
INSERT INTO teams VALUES ('NCAA DIII','Averett University','Danville');
INSERT INTO teams VALUES ('High School','St. Stephens &amp; St. Agnes School','Alexandria');
INSERT INTO teams VALUES ('NCAA DIII','Hampden-Sydney College','Farmville');
INSERT INTO teams VALUES ('NCAA DIII','Christopher Newport University','Newport News');
INSERT INTO teams VALUES ('NCAA DIII','Ferrum College','Ferrum');
INSERT INTO teams VALUES ('NCAA DIII','Washington &amp; Lee University','Lexington');
INSERT INTO teams VALUES ('High School','Southampton High School','Courtland');
INSERT INTO teams VALUES ('High School','Hermitage High School','Henrico');
INSERT INTO teams VALUES ('High School','Kecoughtan High School','Hampton');
INSERT INTO teams VALUES ('High School','Orange County High School','Orange');
INSERT INTO teams VALUES ('High School','Salem High School','Virginia Beach');
INSERT INTO teams VALUES ('High School','Granby High School','Norfolk');
INSERT INTO teams VALUES ('High School','Highland Springs High School','Highland Springs');
INSERT INTO teams VALUES ('High School','Saint John Paul The Great High School','Dumfries');
INSERT INTO teams VALUES ('High School','Galax High School','Galax');
INSERT INTO teams VALUES ('High School','Fork Union Military Academy','Fork Union');
INSERT INTO teams VALUES ('High School','Fauquier High School','Warrenton');
INSERT INTO teams VALUES ('High School','West Potomac High School','Alexandria');
INSERT INTO teams VALUES ('High School','Sherando High School','Stephens City');
INSERT INTO teams VALUES ('High School','Nansemond River High School','Suffolk');
INSERT INTO teams VALUES ('High School','Massaponax High School','Fredericksburg');
INSERT INTO teams VALUES ('High School','Monticello High School','Charlottesville');
INSERT INTO teams VALUES ('High School','Benedictine High School','Richmond');
INSERT INTO teams VALUES ('High School','Kettle Run High School','Nokesville');
INSERT INTO teams VALUES ('High School','Thomas Dale High School','Chester');
INSERT INTO teams VALUES ('High School','Christchurch School','Christchurch');
INSERT INTO teams VALUES ('High School','Grafton High School','Yorktown');
INSERT INTO teams VALUES ('High School','Cosby High School','Midlothian');
INSERT INTO teams VALUES ('High School','Manchester High School','Midlothian');
INSERT INTO teams VALUES ('High School','George Wythe High School','Wytheville');
INSERT INTO teams VALUES ('High School','Glenvar High School','Salem');
INSERT INTO teams VALUES ('High School','Western Branch High School','Chesapeake');
INSERT INTO teams VALUES ('High School','Atlantic Shores High School','Chesapeake');
INSERT INTO teams VALUES ('High School','Monacan High School','Richmond');
INSERT INTO teams VALUES ('High School','Annandale High School','Annandale');
INSERT INTO teams VALUES ('High School','Bluestone High School','Skipwith');
INSERT INTO teams VALUES ('High School','Twin Valley High School','Pilgrim&#39;s Knob');
INSERT INTO teams VALUES ('High School','Hanover High School','Mechanicsville');
INSERT INTO teams VALUES ('High School','Lord Botetourt High School','Daleville');
INSERT INTO teams VALUES ('High School','Warwick High School','Newport News');
INSERT INTO teams VALUES ('High School','Herndon High School','Herndon');
INSERT INTO teams VALUES ('High School','Amherst County High School','Amherst');
INSERT INTO teams VALUES ('High School','Chantilly High School','Chantilly');
INSERT INTO teams VALUES ('High School','Charlottesville High School','Charlottesville');
INSERT INTO teams VALUES ('High School','Giles High School','Pearisburg');
INSERT INTO teams VALUES ('High School','Frank W. Cox High School','Virginia Beach');
INSERT INTO teams VALUES ('High School','Lancaster High School','Lancaster');
INSERT INTO teams VALUES ('High School','Hurley High School','Hurley');
INSERT INTO teams VALUES ('High School','St. Christopher&#39;s School','Richmond');
INSERT INTO teams VALUES ('High School','King William High School','King William');
INSERT INTO teams VALUES ('High School','Massanutten Military Academy','Woodstock');
INSERT INTO teams VALUES ('High School','Rappahannock High School','Warsaw');
INSERT INTO teams VALUES ('High School','Nansemond-Suffolk Academy','Suffolk');
INSERT INTO teams VALUES ('High School','Salem High School','Salem');
INSERT INTO teams VALUES ('High School','St. Anne&#39;s-Belfield School','Charlottesville');
INSERT INTO teams VALUES ('High School','T.C. Williams High School','Alexandria');
INSERT INTO teams VALUES ('High School','Edison High School','Alexandria');
INSERT INTO teams VALUES ('High School','Patrick Henry High School','Ashland');
INSERT INTO teams VALUES ('High School','Northside High School','Roanoke');
INSERT INTO teams VALUES ('High School','Richmond Christian School','Chesterfield');
INSERT INTO teams VALUES ('High School','South Lakes High School','Reston');
INSERT INTO teams VALUES ('High School','Tabb High School','Yorktown');
INSERT INTO teams VALUES ('High School','Park View High School','South Hill');
INSERT INTO teams VALUES ('High School','John S. Battle High School','Bristol');
INSERT INTO teams VALUES ('High School','Matoaca High School','Petersburg');
INSERT INTO teams VALUES ('High School','Patrick Henry High School','Glade Spring');
INSERT INTO teams VALUES ('High School','Dominion High School','Sterling');
INSERT INTO teams VALUES ('High School','Woodside High School','Newport News');
INSERT INTO teams VALUES ('High School','Henrico High School','Richmond');
INSERT INTO teams VALUES ('High School','Radford High School','Radford');
INSERT INTO teams VALUES ('High School','Blacksburg High School','Blacksburg');
INSERT INTO teams VALUES ('High School','George Mason High School','Falls Church');
INSERT INTO teams VALUES ('High School','Goochland High School','Goochland');
INSERT INTO teams VALUES ('High School','Robert E. Lee High School','Staunton');
INSERT INTO teams VALUES ('High School','Randolph-Henry High School','Charlotte Court House');
INSERT INTO teams VALUES ('High School','Prince Edward County High School','Farmville');
INSERT INTO teams VALUES ('High School','Powhatan High School','Powhatan');
INSERT INTO teams VALUES ('High School','Gretna High School','Gretna');
INSERT INTO teams VALUES ('High School','Staunton River High School','Moneta');
INSERT INTO teams VALUES ('High School','Warhill High School','Newport News');
INSERT INTO teams VALUES ('High School','Richlands High School','Richlands');
INSERT INTO teams VALUES ('High School','William Campbell High School','Gladys');
INSERT INTO teams VALUES ('High School','Rye Cove High School','Duffield');
INSERT INTO teams VALUES ('High School','L.C. Bird High School','Chesterfield');
INSERT INTO teams VALUES ('High School','Langley High School','McLean');
INSERT INTO teams VALUES ('High School','Madison High School','Vienna');
INSERT INTO teams VALUES ('High School','King`s Fork High School','Suffolk');
INSERT INTO teams VALUES ('High School','Stonewall Jackson High School','Quicksburg');
INSERT INTO teams VALUES ('High School','Liberty High School','Bedford');
INSERT INTO teams VALUES ('High School','North Cross School','Roanoke');
INSERT INTO teams VALUES ('High School','Atlee High School','Mechanicsville');
INSERT INTO teams VALUES ('High School','Bath County High School','Hot Springs');
INSERT INTO teams VALUES ('High School','Floyd Kellam High School','Virginia Beach');
INSERT INTO teams VALUES ('High School','King George High School','King George');
INSERT INTO teams VALUES ('High School','Luray High School','Luray');
INSERT INTO teams VALUES ('High School','William Monroe High School','Stanardsville');
INSERT INTO teams VALUES ('High School','Appomattox County High School','Appomattox');
INSERT INTO teams VALUES ('High School','Hidden Valley High School','Roanoke');
INSERT INTO teams VALUES ('High School','Robinson High School','Fairfax');
INSERT INTO teams VALUES ('High School','Clarke County High School','Berryville');
INSERT INTO teams VALUES ('High School','Osbourn Park High School','Manassas');
INSERT INTO teams VALUES ('High School','Thomas Walker High School','Ewing');
INSERT INTO teams VALUES ('High School','Tunstall High School','Dry Fork');
INSERT INTO teams VALUES ('High School','Turner Ashby High School','Bridgewater');
INSERT INTO teams VALUES ('High School','York High School','Yorktown');
INSERT INTO teams VALUES ('High School','Narrows High School','Narrows');
INSERT INTO teams VALUES ('High School','Spotsylvania High School','Spotsylvania');
INSERT INTO teams VALUES ('High School','Waynesboro High School','Waynesboro');
INSERT INTO teams VALUES ('High School','Eastside High School','Coeburn');
INSERT INTO teams VALUES ('High School','Louisa County High School','Mineral');
INSERT INTO teams VALUES ('High School','Virginia Episcopal School','Lynchburg');
INSERT INTO teams VALUES ('High School','Greensville County High School','Emporia');
INSERT INTO teams VALUES ('High School','Lakeland High School','Suffolk');
INSERT INTO teams VALUES ('High School','Western Albemarle High School','Crozet');
INSERT INTO teams VALUES ('High School','Honaker High School','Honaker');
INSERT INTO teams VALUES ('High School','James Monroe High School','Fredericksburg');
INSERT INTO teams VALUES ('High School','Phoebus High School','Hampton');
INSERT INTO teams VALUES ('High School','Mount Vernon High School','Alexandria');
INSERT INTO teams VALUES ('High School','Northampton High School','Eastville');
INSERT INTO teams VALUES ('High School','Norview High School','Norfolk');
INSERT INTO teams VALUES ('High School','Stone Bridge High School','Ashburn');
INSERT INTO teams VALUES ('High School','Union High School','Big Stone Gap');
INSERT INTO teams VALUES ('High School','Auburn High School','Riner');
INSERT INTO teams VALUES ('High School','Middlesex High School','Saluda');
INSERT INTO teams VALUES ('High School','Nottoway High School','Crewe');
INSERT INTO teams VALUES ('High School','Park View High School','Sterling');
INSERT INTO teams VALUES ('High School','Strasburg High School','Strasburg');
INSERT INTO teams VALUES ('High School','Central High School','Wise');
INSERT INTO teams VALUES ('High School','Franklin High School','Franklin');
INSERT INTO teams VALUES ('High School','Hopewell High School','Hopewell');
INSERT INTO teams VALUES ('High School','John Marshall High School','Richmond');
INSERT INTO teams VALUES ('High School','Maury High School','Norfolk');
INSERT INTO teams VALUES ('High School','Thomas Jefferson High School','Alexandria');
INSERT INTO teams VALUES ('High School','Broadwater Academy','Exmore');
INSERT INTO teams VALUES ('High School','Craig County High School','New Castle');
INSERT INTO teams VALUES ('High School','George Washington High School','Danville');
INSERT INTO teams VALUES ('High School','Halifax County High School','South Boston');
INSERT INTO teams VALUES ('High School','Hampton Roads Academy','Newport News');
INSERT INTO teams VALUES ('High School','Pulaski County High School','Dublin');
INSERT INTO teams VALUES ('High School','Virginia High School','Bristol');
INSERT INTO teams VALUES ('High School','Gloucester High School','Gloucester');
INSERT INTO teams VALUES ('High School','Yorktown High School','Arlington');
INSERT INTO teams VALUES ('High School','C.D. Hylton High School','Woodbridge');
INSERT INTO teams VALUES ('High School','Godwin High School','Henrico');
INSERT INTO teams VALUES ('High School','John I. Burton High School','Norton');
INSERT INTO teams VALUES ('High School','Lake Taylor High School','Norfolk');
INSERT INTO teams VALUES ('High School','Martinsville High School','Martinsville');
INSERT INTO teams VALUES ('High School','McLean High School','Mclean');
INSERT INTO teams VALUES ('High School','Southampton Academy','Courtland');
INSERT INTO teams VALUES ('High School','Blue Ridge School','Dyke');
INSERT INTO teams VALUES ('High School','Christiansburg High School','Christiansburg');
INSERT INTO teams VALUES ('High School','Fuqua School','Farmville');
INSERT INTO teams VALUES ('High School','Lafayette High School','Williamsburg');
INSERT INTO teams VALUES ('High School','Madison County High School','Madison');
INSERT INTO teams VALUES ('High School','Windsor High School','Windsor');
INSERT INTO teams VALUES ('High School','Woodside High School','Newport News');
INSERT INTO teams VALUES ('High School','Courtland High School','Spotsylvania');
INSERT INTO teams VALUES ('High School','Douglas S. Freeman High School','Richmond');
INSERT INTO teams VALUES ('High School','Handley High School','Winchester');
INSERT INTO teams VALUES ('High School','Heritage High School','Lynchburg');
INSERT INTO teams VALUES ('High School','Liberty High School','Bealeton');
INSERT INTO teams VALUES ('High School','Brunswick High School','Lawrenceville');
INSERT INTO teams VALUES ('High School','Colonial Heights High School','Colonial Heights');
INSERT INTO teams VALUES ('High School','Potomac Falls High School','Sterling');
INSERT INTO teams VALUES ('High School','Ocean Lakes High School','Virginia Beach');
INSERT INTO teams VALUES ('High School','Warhill High School','Williamsburg');
INSERT INTO teams VALUES ('High School','Bishop Ireton High School','Alexandria');
INSERT INTO teams VALUES ('High School','Clintwood High School','Clintwood');
INSERT INTO teams VALUES ('High School','Glen Allen High School','Glen Allen');
INSERT INTO teams VALUES ('High School','Mount Saint Joseph High School','McLean');
INSERT INTO teams VALUES ('High School','Osbourn High School','Manassas');
