CREATE TABLE uva (
    `` VARCHAR(2) CHARACTER SET utf8,
    `Naji_Abdullaha` VARCHAR(22) CHARACTER SET utf8,
    `DE` VARCHAR(2) CHARACTER SET utf8,
    `Column_6_5` VARCHAR(4) CHARACTER SET utf8,
    `Column_235` INT,
    `FR` VARCHAR(2) CHARACTER SET utf8,
    `Jacksonville` VARCHAR(21) CHARACTER SET utf8,
    `FL` VARCHAR(2) CHARACTER SET utf8
);
INSERT INTO uva VALUES ('--','Sonny Abramsona','QB','6-2',210,'FR','Chester','NJ');
INSERT INTO uva VALUES ('--','Christian Baumgardnera','DE','6-6',235,'FR','Longport','NJ');
INSERT INTO uva VALUES ('--','Ethan Blundina','WR','6-3',190,'FR','Charlottesville','VA');
INSERT INTO uva VALUES ('--','Christian Brooksa','DL','6-5',240,'FR','Centreville','VA');
INSERT INTO uva VALUES ('--','Dre Bryanta','LB','6-3',220,'FR','Charlottesville','VA');
INSERT INTO uva VALUES ('--','De''Vante Crossa','QB','6-2',200,'FR','Allentown','PA');
INSERT INTO uva VALUES ('--','Osiris Crutchfielda','DL','6-3',245,'FR','Crozet','VA');
INSERT INTO uva VALUES ('--','Chuck Davisa','CB','5-10',170,'FR','Fairfax','VA');
INSERT INTO uva VALUES ('--','Dillon Davisa','LB','6-2',210,'FR','Bellaire','TX');
INSERT INTO uva VALUES ('--','CJ Eppsa','S','5-11',195,'FR','Chesapeake','VA');
INSERT INTO uva VALUES ('--','Nick Granta','DB','6-3',185,'FR','Spotsylvania','VA');
INSERT INTO uva VALUES ('--','Nash Griffina','PK','6-4',215,'FR','Indianapolis','IN');
INSERT INTO uva VALUES ('--','Michael Guercia','LB','6-2',220,'SO','Franklin Lakes','NJ');
INSERT INTO uva VALUES ('--','Trenton Jenkinsa','OT','6-6',280,'FR','Charlottesville','VA');
INSERT INTO uva VALUES ('--','Patrick Kidda','G','6-4',290,'SO','Woodbridge','VA');
INSERT INTO uva VALUES ('--','Darious Latimorea','CB','6-0',170,'SO','Lawrenceville','GA');
INSERT INTO uva VALUES ('--','Dylan Lea','WR','5-7',165,'SO','Ashburn','VA');
INSERT INTO uva VALUES ('--','Brenton Nelsona','S','5-11',170,'FR','Miami','FL');
INSERT INTO uva VALUES ('--','Dillon Reinkensmeyera','OL','6-6',275,'FR','Highlands Ranch','CO');
INSERT INTO uva VALUES ('--','Dominic Shepparda','LB','6-2',220,'FR','Miami','FL');
INSERT INTO uva VALUES ('--','Alec Shiffletta','DL','6-2',220,'JR','Afton','VA');
INSERT INTO uva VALUES ('--','Tyler Shirleya','LS','6-3',220,'JR','Midlothian','VA');
INSERT INTO uva VALUES ('--','Ben Trenta','OT','6-7',290,'FR','Forest','VA');
INSERT INTO uva VALUES ('--','Rambert Tyreea','WR','6-0',175,'SO','Newport News','VA');
INSERT INTO uva VALUES ('1','Donte Wilkinsa','DT','6-1',300,'SR','Woodbridge','VA');
INSERT INTO uva VALUES ('2','Albert Reida','RB','5-9',215,'SR','Washington','DC');
INSERT INTO uva VALUES ('3','Quin Blandinga','S','6-2',215,'JR','Virginia Beach','VA');
INSERT INTO uva VALUES ('4','Taquan Mizzella','RB','5-10',195,'SR','Virginia Beach','VA');
INSERT INTO uva VALUES ('5','Tim Harrisa','CB','6-2',205,'SR','Richmond','VA');
INSERT INTO uva VALUES ('6','Kurt Benkerta','QB','6-4',230,'JR','Cape Coral','FL');
INSERT INTO uva VALUES ('7','Doni Dowlinga','WR','6-1',215,'JR','Richmond','VA');
INSERT INTO uva VALUES ('8','Keeon Johnsona','WR','6-3',215,'SR','Kannapolis','NC');
INSERT INTO uva VALUES ('9','Andrew Browna','DE','6-4',290,'JR','Chesapeake','VA');
INSERT INTO uva VALUES ('10','Jordan Ellisa','RB','5-11',220,'SO','Suwanee','GA');
INSERT INTO uva VALUES ('11','David Eldridgea','WR','6-1',180,'SO','Bealeton','VA');
INSERT INTO uva VALUES ('13','Chris Peacea','LB','6-1',230,'SO','Newport News','VA');
INSERT INTO uva VALUES ('14','Myles Robinsona','CB','5-11',195,'SO','Olney','MD');
INSERT INTO uva VALUES ('15','Matt Johnsa','QB','6-5',215,'SR','Chalfont','PA');
INSERT INTO uva VALUES ('16','Connor Brewera','QB','6-2',195,'SR','Scottsdale','AZ');
INSERT INTO uva VALUES ('17','Malcolm Cooka','LB','6-1',220,'JR','Richmond','VA');
INSERT INTO uva VALUES ('17','Jamil Kamaraa','WR','6-2',205,'SO','Virginia Beach','VA');
INSERT INTO uva VALUES ('18','Ben Hogga','WR','6-0',170,'SO','Lynchburg','VA');
INSERT INTO uva VALUES ('19','Andre Levronea','WR','6-3',225,'JR','Laurel','MD');
INSERT INTO uva VALUES ('20','Steven Wrighta','DE','6-4',255,'FR','Waycross','GA');
INSERT INTO uva VALUES ('21','Juan Thornhilla','S','6-1',190,'SO','Altavista','VA');
INSERT INTO uva VALUES ('22','Daniel Hamma','RB','5-10',200,'JR','Wytheville','VA');
INSERT INTO uva VALUES ('23','Warren Crafta','WR','6-2',195,'FR','Roanoke','VA');
INSERT INTO uva VALUES ('25','Chris Sharpa','S','6-2',195,'FR','Princeton','NJ');
INSERT INTO uva VALUES ('26','Anthony Callowaya','WR','5-8',160,'JR','Lynchburg','VA');
INSERT INTO uva VALUES ('27','Cory Jonesa','LB','6-5',220,'SO','Washington','DC');
INSERT INTO uva VALUES ('28','Wilfred Waheea','S','5-10',200,'SR','Norfolk','VA');
INSERT INTO uva VALUES ('29','Eric Gallona','LB','6-2',220,'SO','Lakeland','FL');
INSERT INTO uva VALUES ('30','Nicholas Contea','P','6-3',225,'SR','Roanoke','VA');
INSERT INTO uva VALUES ('31','Kareem Gibsona','CB','5-11',170,'FR','Johnstown','PA');
INSERT INTO uva VALUES ('32','Kirk Garnera','CB','5-11',180,'JR','Baltimore','MD');
INSERT INTO uva VALUES ('33','Olamide Zaccheausa','WR','5-8',190,'SO','Philadelphia','PA');
INSERT INTO uva VALUES ('34','Bryce Halla','DB','6-3',200,'FR','Harrisburg','PA');
INSERT INTO uva VALUES ('36','Gladimir Paula','LB','6-2',215,'FR','Philadelphia','PA');
INSERT INTO uva VALUES ('37','Jordan Macka','DB','6-4',205,'FR','Lithonia','GA');
INSERT INTO uva VALUES ('38','Kelvin Raineya','S','6-1',205,'SR','Houston','TX');
INSERT INTO uva VALUES ('39','Chris Moorea','DB','6-2',200,'FR','Ashburn','VA');
INSERT INTO uva VALUES ('40','C.J. Stalkera','LB','6-2',225,'SO','West Chester','OH');
INSERT INTO uva VALUES ('41','Connor Wingo-Reevesa','FB','6-3',225,'SR','Midlothian','VA');
INSERT INTO uva VALUES ('42','Jahvoni Simmonsa','LB','6-1',225,'FR','Virginia Beach','VA');
INSERT INTO uva VALUES ('43','Sean Fitzgeralda','LB','5-11',225,'FR','Falls Church','VA');
INSERT INTO uva VALUES ('44','Tanner Cowleya','WR','6-4',220,'FR','Manasquan','NJ');
INSERT INTO uva VALUES ('45','Reed Kellama','LB','6-1',225,'FR','Richmond','VA');
INSERT INTO uva VALUES ('46','Evan Buttsa','TE','6-4',245,'SO','Newtown Square','PA');
INSERT INTO uva VALUES ('47','Lester Colemana','P','6-5',225,'SO','Martinsville','VA');
INSERT INTO uva VALUES ('50','Jackson Matteoa','C','6-5',290,'SR','Ashburn','VA');
INSERT INTO uva VALUES ('51','Zach Bradshawa','LB','6-3',230,'SR','Damascus','MD');
INSERT INTO uva VALUES ('52','Robert Snydera','LB','6-4',220,'FR','Lawrenceville','GA');
INSERT INTO uva VALUES ('53','Micah Kisera','LB','6-2',240,'JR','Baltimore','MD');
INSERT INTO uva VALUES ('54','Matt Terrella','LB','6-4',225,'FR','Lynchburg','VA');
INSERT INTO uva VALUES ('56','Andre Miles-Redmonda','DT','6-4',275,'SR','Richmond','VA');
INSERT INTO uva VALUES ('57','James Trucillaa','DT','6-1',270,'FR','Erie','PA');
INSERT INTO uva VALUES ('58','Eli Hanbacka','DE','6-4',270,'FR','Ashland','VA');
INSERT INTO uva VALUES ('59','Mark Halla','DE','6-2',260,'SR','Virginia Beach','VA');
INSERT INTO uva VALUES ('62','Sean Karla','G','6-6',300,'SR','Manorville','NY');
INSERT INTO uva VALUES ('65','Ben Knutsona','OL','6-9',310,'FR','Granger','IN');
INSERT INTO uva VALUES ('67','Jack Englisha','OT','6-5',290,'JR','Richmond','VA');
INSERT INTO uva VALUES ('70','Steven Mossa','G','6-4',300,'SO','Fredericksburg','VA');
INSERT INTO uva VALUES ('71','Jack McDonalda','G','6-5',290,'JR','Quincy','MA');
INSERT INTO uva VALUES ('72','Eric Smitha','OT','6-5',300,'SR','Decatur','GA');
INSERT INTO uva VALUES ('74','Ryan Bischoffa','OT','6-6',290,'FR','Plymouth','PA');
INSERT INTO uva VALUES ('76','Michael Mooneya','OT','6-6',295,'SR','Malvern','PA');
INSERT INTO uva VALUES ('77','Jake Fielera','OT','6-5',300,'SO','Parkersburg','WV');
INSERT INTO uva VALUES ('78','R.J. Proctora','C','6-5',305,'FR','Bealeton','VA');
INSERT INTO uva VALUES ('80','Hasise Duboisa','WR','6-3',210,'FR','Irvington','NJ');
INSERT INTO uva VALUES ('81','Joe Reeda','WR','6-3',210,'FR','Charlotte Court House','VA');
INSERT INTO uva VALUES ('82','Braedon Uriea','WR','5-10',175,'SO','Purcellville','VA');
INSERT INTO uva VALUES ('83','Brendan Marshalla','TE','6-5',235,'JR','Gaithersburg','MD');
INSERT INTO uva VALUES ('84','Alex Furbanka','PK','6-0',220,'SO','Fairfax','VA');
INSERT INTO uva VALUES ('85','Cole Blackmana','WR','6-1',195,'FR','Glen Allen','VA');
INSERT INTO uva VALUES ('86','Ross Gardnera','WR','6-3',210,'SO','Mechanicsville','VA');
INSERT INTO uva VALUES ('87','Richard Burneya','TE','6-4',245,'FR','Chesapeake','VA');
INSERT INTO uva VALUES ('88','Ryan Santoroa','WR','6-2',215,'SR','Oak Hill','VA');
INSERT INTO uva VALUES ('89','Sam Haywarda','PK','6-0',165,'JR','Dallas','TX');
INSERT INTO uva VALUES ('90','Jack Powersa','DE','6-5',280,'JR','Santa Cruz','CA');
INSERT INTO uva VALUES ('91','Dylan Simsa','PK','6-0',190,'SR','Lynchburg','VA');
INSERT INTO uva VALUES ('95','Juwan Moyea','LB','6-3',255,'FR','Lilburn','GA');
INSERT INTO uva VALUES ('98','Landan Worda','LB','6-5',245,'FR','Vienna','VA');
INSERT INTO uva VALUES ('99','Joe Spaziania','QB','6-2',210,'SO','Hingham','MA');
